### PR TITLE
Bump veewee/xml requirement, extend build matrix

### LINKED ISSUE #30: "Add additional method metadata" breaks compatibility with veewee/xml <3.0.0
### Bug Report

Current version broken with veewee/xml <3.0.0
 

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | x.y.z

#### Summary

https://github.com/php-soap/wsdl-reader/commit/172ca5bdad9c686005506e30e1bb95baa7da3780 introduces `Soap\WsdlReader\Parser\Definitions\TargetNamespaceParser` which uses `VeeWee\Xml\Dom\Document::locateDocumentElement` which is only available in `veewee/xml` >=3.0.0.
Still, composer.json states compatibility with `veewee/xml` `^2.6 || ^3.0`

#### Current behaviour

```
Fatal error: Uncaught Error: Call to undefined method VeeWee\Xml\Dom\Document::locateDocumentElement() in /src/vendor/php-soap/wsdl-reader/src/Parser/Definitions/TargetNamespaceParser.php:13
```

#### How to reproduce

1. Install php-soap/wsdl-reader with --prefer-lowest
2. Run code generation
3. Boom

#### Expected behaviour

Either properly support < 3.0.0 or change version requirements

### PR DESCRIPTION
**Pull request by lstrojny**
Fixes #30

### CODE REVIEW

**Comment by lstrojny** [comment]
@veewee changed the build matrix to have a better job description

What do you want to do about the errors?

This is from webmozart/assert, a transitive dependency from veewee/xml.

```
+'Deprecated: Use of "static" in callables is deprecated in /home/runner/work/wsdl-reader/wsdl-reader/vendor/webmozart/assert/src/Assert.php on line 1973\n
```

1. Increase version in veewee/xml
2. Require newer version in php-soap/wsdl-reader
3. Ignore deprecation warnings in tests


This comes from phpunit/phpunit not being at least version 10 (transitive through php-soap/engine-integration-tests).

```
Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 2:
  - Element 'phpunit', attribute 'cacheDirectory': The attribute 'cacheDirectory' is not allowed.
  - Element 'phpunit', attribute 'requireCoverageMetadata': The attribute 'requireCoverageMetadata' is not allowed.
  - Element 'phpunit', attribute 'beStrictAboutCoverageMetadata': The attribute 'beStrictAboutCoverageMetadata' is not allowed.

  - Element 'source': This element is not expected.
```

Options:
1. Bump to 10 in php-soap/engine-integration-tests
2. Bump to 10 here

**Comment by lstrojny** [comment]
(Fixed the boolean evaluation issue)

**Comment by veewee** [comment]
@lstrojny 

Bumping to phpunit 10 would be some work in verious repos I suppose. It's on my radar, but I'm trying to get some other things (soap encoding) ready first.

Maybe better to provide alternative ranges for both phpunit and assert inside this package's composer.json for now?

**Comment by lstrojny** [comment]
@veewee bumped the relevant dependencies

**Comment by lstrojny** [comment]
Needed to bump phpunit to 10.1, not 10.0. Let's see …

**Comment by veewee** [comment]
Looks good, thanks for the effort (again) !

**Pull request merged**
